/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto;

import static crypto.Caeser.*;
import static crypto.Vigenere.*;



/**
 *
 * @author Eng_Rehab
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        nn.setText("for Caesar cipher: the key is number");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        crypt_type = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        pp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        cc = new javax.swing.JTextArea();
        nn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("encryption/decryption type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 67, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER TEXT:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KEY:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CIPHER TEXT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        kk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkActionPerformed(evt);
            }
        });
        getContentPane().add(kk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 234, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("ENCRYPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 110, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 100, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("DECRYPT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 120, 40));

        crypt_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caesar Cipher", "Vigenere Cipher" }));
        crypt_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crypt_typeActionPerformed(evt);
            }
        });
        getContentPane().add(crypt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 64, 209, -1));

        pp.setColumns(20);
        pp.setRows(5);
        jScrollPane1.setViewportView(pp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 260, 187));

        cc.setColumns(20);
        cc.setRows(5);
        jScrollPane2.setViewportView(cc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 300, 187));
        getContentPane().add(nn, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 98, 320, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CIPHER ENCRYPTION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 226, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crypto/ee.jpg"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cc.setText("");
        pp.setText("");
        kk.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int t = crypt_type.getSelectedIndex();
        switch (crypt_type.getItemAt(t)) {
            case "Caesar Cipher":
                String s = pp.getText();
                int k = Integer.parseInt(kk.getText());
                cc.setText(Caeser_enc(s, k));
                break;
           
            case "Vigenere Cipher":
                String str = pp.getText();
                String keyword = kk.getText();
                String key = generateKey(str, keyword);
                cc.setText(cipherText(str, key));
                break;
            default:
                nn.setText("error!!!!!!!!!!! ^-^");
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int t = crypt_type.getSelectedIndex();
        switch (crypt_type.getItemAt(t)) {
            case "Caesar Cipher":
                String s = cc.getText();
                int k = Integer.parseInt(kk.getText());
                pp.setText(Caeser_dec(s, k));
                break;
         
            case "Vigenere Cipher":
                String cipher_text = cc.getText();
                String keyword = kk.getText();
                String key = generateKey(cipher_text, keyword);
                pp.setText(originalText(cipher_text, key));
                break;
            default:
                nn.setText("error!!!!!!!!!!! ^-^");
                break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void crypt_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crypt_typeActionPerformed
        int t = crypt_type.getSelectedIndex();
        switch (crypt_type.getItemAt(t)) {
            case "Caesar Cipher":
                nn.setText("for Caesar cipher: the key is number");
                break;
            case "Playfair Cipher":
                nn.setText("for Playfair Cipher: encryption key (min length 6)");
                break;
            case "Vigenere Cipher":
                nn.setText("for Vigenere Cipher: Enter only uper-case letters");
                break;
            default:
                nn.setText("for Caesar cipher: the key is number");
                break;
        }
    }//GEN-LAST:event_crypt_typeActionPerformed

    private void kkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cc;
    private javax.swing.JComboBox<String> crypt_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kk;
    private javax.swing.JTextField nn;
    private javax.swing.JTextArea pp;
    // End of variables declaration//GEN-END:variables
}
